services:
  - type: web
    name: tradeguess-backend
    env: docker
    dockerfilePath: ./TradeGuess/backend/Dockerfile
    dockerContext: ./TradeGuess/backend
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
    healthCheckPath: /manage/health
    autoDeploy: true

  - type: web
    name: tradeguess-frontend
    env: docker
    dockerfilePath: ./TradeGuess/frontend/Dockerfile
    dockerContext: ./TradeGuess/frontend              
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://tradeguess-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
