services:
  - type: web
    name: tradeguess-backend
    env: docker
    dockerfilePath: ./TradeGuess/backend/Dockerfile
    dockerContext: ./TradeGuess/backend
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: BINANCE_ENABLED
        value: "false"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
    healthCheckPath: /manage/health
    autoDeploy: true

  - type: web
    name: tradeguess-frontend
    env: docker
    dockerfilePath: ./TradeGuess/frontend/Dockerfile
    dockerContext: ./TradeGuess/frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://tradeguess-backend.onrender.com

    autoDeploy: true