spring:
  application:
    name: tradeguess-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/tradeguess
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass123
      timeout: 5000ms

  cache:
    type: redis
    redis:
      cache-null-values:
      time-to-live: 1h
      key-prefix: "tradeguess:"
      use-key-prefix: true

server:
  port: 8080

logging:
  level:
    com.app.tradeguess: DEBUG
    org.springframework.cache: TRACE

token:
  signin:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855