services:
  - type: web
    name: tradeguess-frontend
    env: docker
    dockerfilePath: ../docker/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://tradeguess-backend.onrender.com
      - key: VITE_TELEGRAM_BOT_TOKEN
        value: 8570348994:AAHvBdSU2e5TwmmZO1yntee41HtxxQjgipU
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true